
version: 2
updates:
  - package-ecosystem: pip # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "12:00"
